// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecipeAPI.Models;

#nullable disable

namespace RecipeAPI.Migrations
{
    [DbContext(typeof(DishesDBContext))]
    [Migration("20230411124513_third")]
    partial class third
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RecipeAPI.Models.CookingMethod", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.ToTable("CookingMethods");
                });

            modelBuilder.Entity("RecipeAPI.Models.Dish", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("complexity")
                        .HasColumnType("int");

                    b.Property<int>("cookingMethodId")
                        .HasColumnType("int");

                    b.Property<string>("dishName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("efficiency")
                        .HasColumnType("int");

                    b.Property<int>("time")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("cookingMethodId");

                    b.ToTable("Dishes");
                });

            modelBuilder.Entity("RecipeAPI.Models.Dish", b =>
                {
                    b.HasOne("RecipeAPI.Models.CookingMethod", "CookingMethod")
                        .WithMany("Dishes")
                        .HasForeignKey("cookingMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CookingMethod");
                });

            modelBuilder.Entity("RecipeAPI.Models.CookingMethod", b =>
                {
                    b.Navigation("Dishes");
                });
#pragma warning restore 612, 618
        }
    }
}
